name: blog
description: "FREE ONLINE COURSES"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  avatar_glow: ^3.0.1
  in_app_update: ^4.2.5
  animated_bottom_navigation_bar:
    path: ./animated_bottom_navigation_bar
  cached_network_image: ^3.4.1
  flutter_icons:
    path: ./flutter_icons
  connectivity_plus: ^7.0.0
  share: ^2.0.4
  cloud_firestore: ^6.0.3
  permission_handler: ^12.0.1
  dots_indicator: ^4.0.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_html: ^3.0.0
  intl: ^0.20.2
  google_fonts: ^6.3.2
  google_sign_in: ^6.2.1
  line_icons: ^2.0.3
  provider: ^6.1.5+1
  device_info_plus: ^12.2.0

  html_unescape: ^2.0.0
  flutter_widget_from_html: ^0.17.1
  shared_preferences: ^2.5.3
  skeleton_text: ^3.0.1

  toast: ^0.3.0
  url_launcher: ^6.3.2
  introduction_screen: ^4.0.0
  youtube_player_flutter: ^9.1.3
  focused_menu: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Muli
      fonts:
        - asset: fonts/Muli-Regular.ttf
          weight: 500
        - asset: fonts/Muli-Medium.ttf
          weight: 600
        - asset: fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: fonts/Muli-Bold.ttf
          weight: 800
